# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: Publish Android Release
description: Uploads an Android release artifact to the Google Play Console
author: deep.rent GmbH

branding:
  icon: upload
  color: green

inputs:
  project-directory:
    description: 'Path to the root Android project directory containing the gradlew executable.'
    required: true
    default: '.'
  keystore:
    description: 'Base64-encoded string representation of your Android release keystore (e.g., .jks or .keystore) file.'
    required: true
  keystore-password:
    description: 'The password required to unlock the Android keystore.'
    required: true
  key-alias:
    description: 'The alias of the signing key stored within the keystore.'
    required: true
  key-password:
    description: 'The password for the specific signing key alias.'
    required: true
  service-account:
    description: 'The plain text JSON contents of the Google Cloud Service Account used to authenticate with the Google Play Developer API.'
    required: true
  package-name:
    description: 'The application ID (package name) of the Android app (e.g., com.example.app).'
    required: true
  track:
    description: 'The Google Play track to publish the release to. Valid options are: internal, alpha, beta, production.'
    required: true
    default: 'internal'
  status:
    description: 'The status of the release. Valid options are: completed, draft, halted, inProgress.'
    required: true
    default: 'completed'
outputs:
  version-code:
    description: 'The assigned version code of the successfully uploaded Android App Bundle (AAB).'
  aab-path:
    description: 'The absolute local path to the generated and signed Android App Bundle (AAB) file.'

runs:
  using: node24
  main: dist/index.js
